#ifndef _ERROR_CODES_H_
#define _ERROR_CODES_H_

//IO errors
#define ERROR_INVALID_FILEPATH_PARAMETER -1
#define ERROR_INVALID_FILESTREAM_PARAMETER -2
#define ERROR_CANNOT_OPEN_FILE_FOR_WRITE -3
#define ERROR_CANNOT_OPEN_FILE_FOR_READ -4
#define ERROR_INPUT_FILESTREAM_IS_NOT_OGG_STREAM -5
#define ERROR_READING_OGG_STREAM -6

//Other errors
#define ERROR_INVALID_SAMPLES_PARAMETER -10
#define ERROR_INVALID_SAMPLESLENGTH_PARAMETER -11
#define ERROR_INVALID_CHANNELS_PARAMETER -12
#define ERROR_INVALID_FREQUENCY_PARAMETER -13
#define ERROR_INVALID_BASE_QUALITY_PARAMETER -14


#endif // !_ERROR_CODES_H_
