#ifndef _ERROR_CODES_H_
#define _ERROR_CODES_H_

//IO errors
#define ERROR_INVALID_FILEPATH_PARAMETER -1
#define ERROR_CANNOT_OPEN_FILE_FOR_WRITE -2
#define ERROR_CANNOT_OPEN_FILE_FOR_READ -3
#define ERROR_INPUT_FILESTREAM_IS_NOT_OGG_STREAM -4
#define ERROR_READING_OGG_STREAM -5

//Other errors
#define ERROR_INVALID_SAMPLES_PARAMETER -10
#define ERROR_INVALID_SAMPLESLENGTH_PARAMETER -11
#define ERROR_INVALID_CHANNELS_PARAMETER -12
#define ERROR_INVALID_FREQUENCY_PARAMETER -13
#define ERROR_INVALID_BASE_QUALITY_PARAMETER -14
#define ERROR_MALLOC_RETURNED_NULL -15
#define ERROR_BYTES_MEMORY_ARRAY_NULL -16
#define ERROR_INVALID_WRITE_CALLBACK_PARAMETER -17


#endif // !_ERROR_CODES_H_
